services:

  client:
    container_name: client_app
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
      - app
    ports:
      - "5173:5173"
    networks:
      - postgres

  app:
    container_name: python_app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CLIENT_HOST: ${CLIENT_HOST}
      CLIENT_PORT: ${CLIENT_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_FILE: ${LOG_FILE}
      TEST_DB_HOST: ${TEST_DB_HOST}
      TEST_DB_PORT: ${TEST_DB_PORT}
      TEST_DB_NAME: ${TEST_DB_NAME}
      TEST_DB_USER: ${TEST_DB_USER}
      TEST_DB_PASSWORD: ${TEST_DB_PASSWORD}

    build:
      context: ./server
      dockerfile: Dockerfile
    command: |
      bash -c "
      poetry run celery -A src.celery_tasks worker --loglevel=info -B --detach &&
      poetry run alembic upgrade head &&
      poetry run uvicorn src.main:app --host 0.0.0.0 --port 8000
      "
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    networks:
      - postgres

  db:
    image: postgres:15.7
    container_name: postgres_app
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - ${DB_PORT}:5432
    volumes:
      - python-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - postgres

  redis:
    image: redis
    container_name: redis_app
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - postgres
    volumes:
      - redis-data:/data

volumes:
  python-data:
  redis-data:


networks:
  postgres:
    driver: bridge
