services:
  db:
    image: postgres:15.7
    container_name: postgres_app_dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - python-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 10s
      retries: 5

  test_db:
    image: postgres:15.7
    container_name: postgres_test_db
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - ${TEST_DB_PORT}:5432
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}"
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  redis:
    image: redis
    container_name: redis_app_dev
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data

volumes:
  python-data:
  redis_data:
