"""rename

Revision ID: 2f5b637e8dd4
Revises: 9b46a784e8d8
Create Date: 2024-04-02 19:02:49.919165

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f5b637e8dd4"
down_revision: Union[str, None] = "9b46a784e8d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks_group", "is_active", default=False, new_column_name="is_done"
    )
    op.drop_column("task", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks_group", "is_done", default=False, new_column_name="is_active"
    )
    op.drop_column("tasks_group", "is_done")
    op.add_column(
        "task", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
