"""deadline for tasks group

Revision ID: 05bd0260615a
Revises: 35cf48d6b722
Create Date: 2024-04-24 12:10:19.319938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05bd0260615a'
down_revision: Union[str, None] = '35cf48d6b722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_group', sa.Column('deadline', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks_group', 'deadline')
    # ### end Alembic commands ###
