"""add column deadline

Revision ID: 35cf48d6b722
Revises: a1c99312a5d2
Create Date: 2024-04-18 17:11:50.653621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35cf48d6b722'
down_revision: Union[str, None] = 'a1c99312a5d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('deadline', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'deadline')
    # ### end Alembic commands ###
