"""modify User model

Revision ID: fe546de643f7
Revises: d24e5311e6c1
Create Date: 2024-03-14 11:35:26.779464

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe546de643f7"
down_revision: Union[str, None] = "d24e5311e6c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "tasks_group", ["id"])
    op.create_unique_constraint(None, "users", ["id"])

    # ### my commands ###
    op.alter_column("users", "name", nullable=False, new_column_name="firstname")
    op.alter_column("users", "surname", nullable=False, new_column_name="lastname")
    op.alter_column("users", "username", nullable=False, new_column_name="login")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "tasks_group", type_="unique")
    # ### end Alembic commands ###
