"""NULL

Revision ID: 9b46a784e8d8
Revises: 4d42bbee8ebf
Create Date: 2024-03-27 16:21:06.359355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b46a784e8d8'
down_revision: Union[str, None] = '4d42bbee8ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'firstname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
